### ISSUE TITLE
CheckWX seemed to update it's API

### ISSUE THREAD

**Issue by XploD-Ing** [destotelhorus/DCS-WeatherInjector#2]
**Describe the bug**
Since 28.07.2020, the Weather Injectors fails with the message
KeyError: 'celsius'
As it looks, checkwx sometimes returns ['temperature']['minimum']['celsius'], while on over regions, it returns ['temperature']['celsius']

The message is caused by Line 67 of DCSCheckWXConvertEnricher.py
    def getTemperature(self):
        return self.getClosestResult()['temperature']['celsius']

To fix it, I tried following: 
    def getTemperature(self):
        closest_data = self.getClosestResult()
        if hasattr(closest_data['temperature'],'celsius'):
             return closest_data['temperature']['celsius']
        if hasattr(closest_data['temperature'],'minimum'):
             return closest_data['temperature']['minimum']['celsius']
        return 21

**Comment by destotelhorus** [comment]
I applied your solution!

Thank you very much for your contribution!
