### ISSUE TITLE
Add Syria to Script

### ISSUE THREAD

**Issue by XploD-Ing** [destotelhorus/DCS-WeatherInjector#3]
Today, Syria was released for open beta.

I added following line to MIZFile.py: line 63 to support it: 
      elif self.getTheatre() == 'Syria':
            return {"lat": 33.510414, "lon": 36.278336}

The values should be for Damaskus, I hope these values are correct.

Best regards,
JG78_Plotti

**Comment by destotelhorus** [comment]
Awesome, thank you for your contribution. I'll add that right away.
Do you happen to have the "name" and the coords for the channel map as well, as I don't have that.

**Comment by XploD-Ing** [comment]
> Do you happen to have the "name" and the coords for the channel map as well, as I don't have that.
Yes, I am proud owner of the syria map (If you've got the money, I just can recommend this map. It has an awful amound of love for details ( e.g. the runways aren't flat, they are curved and go slightly uphill, like real runways. Houses and trees aren't all the same , ...)

But what do you mean with name and coords? A mission states "Syria" in the thatre.lua file. I can send you a sample mission or the debug output of the RealWeather script, if you need.

Fly save.
Plotti
